services:
  jupyter-notebook:
    image: docker.io/tstuckey303/scs-analysis-jupyter:1.27
    container_name: analysis_container_jupyter
    ports:
      - "7321:8888"
    volumes:
      - "./_admin:/home/jovyan/_admin"
      - "./_data:/home/jovyan/_data"
      - "./notebooks:/home/jovyan/notebooks"
    restart: unless-stopped
